//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsMedical.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.doctor = new HashSet<doctor>();
            this.school = new HashSet<school>();
            this.student = new HashSet<student>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<doctor> doctor { get; set; }
        public virtual ICollection<school> school { get; set; }
        public virtual ICollection<student> student { get; set; }
    }
}
