//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsMedical.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rfidEntities : DbContext
    {
        public rfidEntities()
            : base("name=rfidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<absmedical> absmedical { get; set; }
        public DbSet<country> country { get; set; }
        public DbSet<doctor> doctor { get; set; }
        public DbSet<school> school { get; set; }
        public DbSet<student> student { get; set; }
        public DbSet<visit> visit { get; set; }
    }
}
