//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsMedical.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public visit()
        {
            this.absmedical = new HashSet<absmedical>();
        }
    
        public System.DateTime VisitDate { get; set; }
    
        public virtual ICollection<absmedical> absmedical { get; set; }
    }
}
