//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsMedical.SchoolServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchoolServiceReference.ISchoolService")]
    public interface ISchoolService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetSchool", ReplyAction="http://tempuri.org/ISchoolService/GetSchoolResponse")]
        AbsMedical.WCF.School GetSchool(string schoolGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetSchool", ReplyAction="http://tempuri.org/ISchoolService/GetSchoolResponse")]
        System.Threading.Tasks.Task<AbsMedical.WCF.School> GetSchoolAsync(string schoolGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetSchoolsByCountry", ReplyAction="http://tempuri.org/ISchoolService/GetSchoolsByCountryResponse")]
        System.Collections.Generic.List<AbsMedical.WCF.School> GetSchoolsByCountry(string countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetSchoolsByCountry", ReplyAction="http://tempuri.org/ISchoolService/GetSchoolsByCountryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AbsMedical.WCF.School>> GetSchoolsByCountryAsync(string countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetSchools", ReplyAction="http://tempuri.org/ISchoolService/GetSchoolsResponse")]
        System.Collections.Generic.List<AbsMedical.WCF.School> GetSchools();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetSchools", ReplyAction="http://tempuri.org/ISchoolService/GetSchoolsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AbsMedical.WCF.School>> GetSchoolsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchoolServiceChannel : AbsMedical.SchoolServiceReference.ISchoolService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchoolServiceClient : System.ServiceModel.ClientBase<AbsMedical.SchoolServiceReference.ISchoolService>, AbsMedical.SchoolServiceReference.ISchoolService {
        
        public SchoolServiceClient() {
        }
        
        public SchoolServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchoolServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AbsMedical.WCF.School GetSchool(string schoolGuid) {
            return base.Channel.GetSchool(schoolGuid);
        }
        
        public System.Threading.Tasks.Task<AbsMedical.WCF.School> GetSchoolAsync(string schoolGuid) {
            return base.Channel.GetSchoolAsync(schoolGuid);
        }
        
        public System.Collections.Generic.List<AbsMedical.WCF.School> GetSchoolsByCountry(string countryId) {
            return base.Channel.GetSchoolsByCountry(countryId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AbsMedical.WCF.School>> GetSchoolsByCountryAsync(string countryId) {
            return base.Channel.GetSchoolsByCountryAsync(countryId);
        }
        
        public System.Collections.Generic.List<AbsMedical.WCF.School> GetSchools() {
            return base.Channel.GetSchools();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AbsMedical.WCF.School>> GetSchoolsAsync() {
            return base.Channel.GetSchoolsAsync();
        }
    }
}
